import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="3xl:w-[100%] 2xl:w-[100%]">
        <div className="min-w-full">
          <Header />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
